#define RB_CHARLES 100
#define RB_BOYLES 101

//NUMBER OF GAS MOLES B and C
#define ID_NUMGASMOLESB 102
#define ID_NUMGASMOLESC 103

//INCREMENT DECREMENT B and C
#define ID_INCDECB 104
#define ID_INCDECC 105

//TEMPRATURE B and C
#define ID_TEMPB 106
#define ID_TEMPC 107

//PRESSURE B and C
#define ID_PRESSUREB 108
#define ID_PRESSUREC 109

//PUSH PLUS/MINUS FOR PRESSURE BUTTON B 
#define ID_PRESSUREPLUSB 110
#define ID_PRESSUREMINUSB 111

//PUSH PLUS/MINUS FOR PRESSURE BUTTON C
#define ID_PLUSC 112
#define ID_MINUSC 113

//VOLUME B and C
#define ID_VOLUMEB 114
#define ID_VOLUMEC 115

//PUSH PLUS/MINUS FOR BUTTON VOLUME  B 
#define ID_VPLUSB 116
#define ID_VMINUSB 117

//PUSH PLUS/MINUS FOR BUTTON VOLUME C
#define ID_VPLUSC 118
#define ID_VMINUSC 119

//PUSH PLUS/MINUS TEMPRATURE 
#define ID_TPLUSC 120
#define ID_TMINUSC 121


//PUSH SAVETOFILE RESET BUTTON B
#define ID_FILEB 122
#define ID_RESETB 123

//PUSH SAVETOFILE RESET BUTTON C
#define ID_FILEC 124
#define ID_RESETC 125

#define ID_GROUPBOX1 126
#define ID_GROUPBOX2 127
 
#define ID_CANCEL 128
#define ID_PBCONTINUE 129
#define ID_OK 130
#define IDB_BITMAP_SPLASH 131




